version: '2'
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/nginx-snippets:/etc/nginx/snippets:ro
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    ports:
      - "127.0.0.1:9229:9229" # V8 inspector for tools/run.js
      - "127.0.0.1:9230:9230" # V8 inspector for src/serer.js
    volumes:
      - ./api/:/usr/src/app
    command: sh -c "tools/wait-for-pg.sh db -- yarn db-migrate && yarn start"
    hostname: api
  db:
    read_only: true
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - database:/var/lib/postgresql/data
    hostname: db
  ui:
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app
    environment:
      - USE_LDAP=true
    # command: serve -s build -p 3000
    # build:
      # dockerfile: Dockerfile-prod
    hostname: ui
  redis:
    image: redis:3.2.9-alpine
    read_only: true
    volumes:
      - redis:/data
    user: redis
    hostname: redis