FROM node:8.1.2
RUN yarn global add serve

WORKDIR /usr/src/app

COPY package.json yarn.lock /tmp/
RUN cd /tmp && yarn install
RUN mkdir -p /usr/src/app && cd /usr/src/app && ln -s /tmp/node_modules

COPY ./ /usr/src/app

RUN yarn build

CMD ["serve", "-s" "build"]


