FROM node:8.1.2-alpine

RUN apk --update add postgresql-client docker && rm -rf /var/cache/apk/*
RUN mkdir -p /usr/src/app && cd /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN chmod +x /usr/src/app/tools/wait-for-pg.sh

CMD [ "tools/wait-for-pg.sh", "db", "--", "yarn db-migrate && node build/server.js" ]
